hl.on("hyprland.start", function () 
    hl.exec_cmd(terminal .. "--class term1")
    hl.exec_cmd(chromium)
    hl.exec_cmd(brave)
    hl.exec_cmd(obsidian)
    hl.exec_cmd(code)
--    hl.exec_cmd(slack)
--    hl.exec_cmd("bruno")
hl.exec_cmd("nm-applet")
   hl.exec_cmd("qs & hyperpaper")
end)